# Generated by Django 4.0.2 on 2022-02-25 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('state', models.CharField(choices=[('hot', 'Hot Lead'), ('cold', 'Cold Lead'), ('med', 'Med Lead'), ('sold', 'Sold'), ('new', 'New')], default='new', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.IntegerField(null=True, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('user_type', models.CharField(choices=[('none', 'None'), ('admin', 'sales_admin'), ('representative', 'sales_representative')], default='none', max_length=32)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(blank=True, null=True)),
                ('user_bio', models.CharField(blank=True, max_length=200, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.salesuser')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.salesuser')),
            ],
            options={
                'ordering': ['-updated', 'created'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.salesuser'),
        ),
    ]
