# Generated by Django 4.0.2 on 2022-03-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_salesuser_options_alter_salesuser_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='email_address',
            new_name='email',
        ),
    ]
